
#ifndef _RESOURCES_H_
#define _RESOURCES_H_

#define wxID_NOTEBOOK					wxID_HIGHEST + 2
#define wxID_TAB_WINDOW					wxID_HIGHEST + 3
#define wxID_TAB_DX9					wxID_HIGHEST + 4

#define wxID_COMBO_DX9ADAPTERS			wxID_HIGHEST + 5
#define wxID_COMBO_WINDOWRES			wxID_HIGHEST + 6
#define wxID_CHECKBOX_FULLSCREEN		wxID_HIGHEST + 7
#define wxID_COMBO_RENDERPLUGIN			wxID_HIGHEST + 8
#define wxID_STATICTEXT_RENDERPLUGIN	wxID_HIGHEST + 9

#define wxID_BUTTON_SAVE				wxID_HIGHEST + 10

#define wxID_STATICTEXT_DX9ADAPTERDESCR	wxID_HIGHEST + 11
#define wxID_LISTBOX_DX9ADAPTERMODES	wxID_HIGHEST + 12
#define wxID_STATICTEXT_SELECTEDMODE	wxID_HIGHEST + 13
#define wxID_STATICTEXT_VERTEXPROC		wxID_HIGHEST + 14
#define wxID_COMBO_VERTEXPROC			wxID_HIGHEST + 15

#endif
