/*
*                                                                          
* DrawSpace Rendering engine                                               
* Emmanuel Chaumont Copyright (c) 2013-2014                                
*                                                                          
* This file is part of DrawSpace.                                          
*                                                                          
*    DrawSpace is free software: you can redistribute it and/or modify     
*    it under the terms of the GNU General Public License as published by  
*    the Free Software Foundation, either version 3 of the License, or     
*    (at your option) any later version.                                   
*                                                                          
*    DrawSpace is distributed in the hope that it will be useful,          
*    but WITHOUT ANY WARRANTY; without even the implied warranty of        
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
*    GNU General Public License for more details.                          
*                                                                          
*    You should have received a copy of the GNU General Public License     
*    along with DrawSpace.  If not, see <http://www.gnu.org/licenses/>.    
*                                                                          
*/

#ifndef __BasicScenePanel__
#define __BasicScenePanel__

/**
@file
Subclass of Panel, which is generated by wxFormBuilder.
*/

#include "panel.h"

class BasicScenePanel : public Panel
{
protected:

    virtual void OnAssetsListItemActivated( wxListEvent& p_event );
            
public:
    
    BasicScenePanel( wxWindow* parent );

    void Update( void );
	
};

#endif // __MyProject1Panel__
