#ifndef __BasicScenePanel__
#define __BasicScenePanel__

/**
@file
Subclass of Panel, which is generated by wxFormBuilder.
*/

#include "panel.h"

//// end generated include

/** Implementing Panel */
class BasicScenePanel : public Panel
{
protected:



	public:
		/** Constructor */
		BasicScenePanel( wxWindow* parent );
	//// end generated class members
	
};

#endif // __MyProject1Panel__
